### ISSUE TITLE
Malformed JSON received from ScreenInvader

### ISSUE THREAD

**Issue by phaer** [kallaballa/Janosh#13]
I'm posting this issue to this repo, because Janosh should never return malformed json. I'm going to look into this later on, looks like a problem with with "url". Maybe it's related to #3 ?

<code>
{ "active":"false","category":" ","url":" " } ,"browser": { "active":"false","category":"image","url":"http://10.20.30.90/img/power_down_warning.png" } ,"clients": [ "test","BLA" ] ,"display": { "blank":"false","resolution":"1920x1080" } ,"image": { "active":"false","category":"","url":"" } ,"pdf": { "active":"false","category":"","url":"" } ,"player": { "active":"true","category":"youtube","url":"http://youtu.be/IkYfB1C0Zgc" } ,"playlist": { "index":"128","items": [ { "source":"http://www.youtube.com/watch?v=6KKKGpAZHAA","title":"OVERWERK - Daybreak (GoPro HERO3 Edit) [Electro House]","url":"http://r6---sn-uxaxufv-8pxe.googlevideo.com/videoplayback?ratebypass=yes&expire=1426805268&sver=3&dur=304.088&pl=19&ipbits=0&signature=E092A4BB3C79E3AB0EDC78C2425B7A0CFAAEEF78.4FA007BCAC2FDF87A57BAAECFD1BF478F6A006DE&itag=22&mm=31&requiressl=yes&mime=video%2Fmp4&source=youtube&ms=au&key=yt5&mv=m&mt=1426783576&fexp=900720%2C905648%2C907263%2C934954%2C9406733%
</code>

**Comment by kallaballa** [comment]
That's an issue with the janosh cache. when i disable it responses are fine. i'll investigate more

**Comment by kallaballa** [comment]
i disabled the db cache entirely - performance is still good enough. i'll fix it after #8 is fixed.
